// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: milestones.sql

package db

import (
	"context"
)

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (
    id,
    title,
    status,
    phase,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, title, status, phase, created_at, updated_at
`

type CreateMilestoneParams struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Status string `json:"status"`
	Phase  string `json:"phase"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.queryRow(ctx, q.createMilestoneStmt, createMilestone,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.Phase,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones
WHERE id = ?
`

func (q *Queries) DeleteMilestone(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMilestoneStmt, deleteMilestone, id)
	return err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, title, status, phase, created_at, updated_at FROM milestones
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMilestone(ctx context.Context, id string) (Milestone, error) {
	row := q.queryRow(ctx, q.getMilestoneStmt, getMilestone, id)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMilestones = `-- name: ListMilestones :many
SELECT id, title, status, phase, created_at, updated_at FROM milestones
ORDER BY created_at DESC
`

func (q *Queries) ListMilestones(ctx context.Context) ([]Milestone, error) {
	rows, err := q.query(ctx, q.listMilestonesStmt, listMilestones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMilestonePhase = `-- name: UpdateMilestonePhase :one
UPDATE milestones
SET phase = ?
WHERE id = ?
RETURNING id, title, status, phase, created_at, updated_at
`

type UpdateMilestonePhaseParams struct {
	Phase string `json:"phase"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateMilestonePhase(ctx context.Context, arg UpdateMilestonePhaseParams) (Milestone, error) {
	row := q.queryRow(ctx, q.updateMilestonePhaseStmt, updateMilestonePhase, arg.Phase, arg.ID)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMilestoneStatus = `-- name: UpdateMilestoneStatus :one
UPDATE milestones
SET status = ?
WHERE id = ?
RETURNING id, title, status, phase, created_at, updated_at
`

type UpdateMilestoneStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateMilestoneStatus(ctx context.Context, arg UpdateMilestoneStatusParams) (Milestone, error) {
	row := q.queryRow(ctx, q.updateMilestoneStatusStmt, updateMilestoneStatus, arg.Status, arg.ID)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
