// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slices.sql

package db

import (
	"context"
	"database/sql"
)

const createSlice = `-- name: CreateSlice :one
INSERT INTO slices (
    id,
    milestone_id,
    title,
    status,
    phase,
    sort_order,
    depends_on,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, milestone_id, title, status, phase, sort_order, depends_on, created_at, updated_at
`

type CreateSliceParams struct {
	ID          string         `json:"id"`
	MilestoneID string         `json:"milestone_id"`
	Title       string         `json:"title"`
	Status      string         `json:"status"`
	Phase       string         `json:"phase"`
	SortOrder   int64          `json:"sort_order"`
	DependsOn   sql.NullString `json:"depends_on"`
}

func (q *Queries) CreateSlice(ctx context.Context, arg CreateSliceParams) (Slice, error) {
	row := q.queryRow(ctx, q.createSliceStmt, createSlice,
		arg.ID,
		arg.MilestoneID,
		arg.Title,
		arg.Status,
		arg.Phase,
		arg.SortOrder,
		arg.DependsOn,
	)
	var i Slice
	err := row.Scan(
		&i.ID,
		&i.MilestoneID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.SortOrder,
		&i.DependsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSlice = `-- name: DeleteSlice :exec
DELETE FROM slices
WHERE id = ?
`

func (q *Queries) DeleteSlice(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSliceStmt, deleteSlice, id)
	return err
}

const getSlice = `-- name: GetSlice :one
SELECT id, milestone_id, title, status, phase, sort_order, depends_on, created_at, updated_at FROM slices
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSlice(ctx context.Context, id string) (Slice, error) {
	row := q.queryRow(ctx, q.getSliceStmt, getSlice, id)
	var i Slice
	err := row.Scan(
		&i.ID,
		&i.MilestoneID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.SortOrder,
		&i.DependsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSlicesByMilestone = `-- name: ListSlicesByMilestone :many
SELECT id, milestone_id, title, status, phase, sort_order, depends_on, created_at, updated_at FROM slices
WHERE milestone_id = ?
ORDER BY sort_order
`

func (q *Queries) ListSlicesByMilestone(ctx context.Context, milestoneID string) ([]Slice, error) {
	rows, err := q.query(ctx, q.listSlicesByMilestoneStmt, listSlicesByMilestone, milestoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slice{}
	for rows.Next() {
		var i Slice
		if err := rows.Scan(
			&i.ID,
			&i.MilestoneID,
			&i.Title,
			&i.Status,
			&i.Phase,
			&i.SortOrder,
			&i.DependsOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSlicePhase = `-- name: UpdateSlicePhase :one
UPDATE slices
SET phase = ?
WHERE id = ?
RETURNING id, milestone_id, title, status, phase, sort_order, depends_on, created_at, updated_at
`

type UpdateSlicePhaseParams struct {
	Phase string `json:"phase"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateSlicePhase(ctx context.Context, arg UpdateSlicePhaseParams) (Slice, error) {
	row := q.queryRow(ctx, q.updateSlicePhaseStmt, updateSlicePhase, arg.Phase, arg.ID)
	var i Slice
	err := row.Scan(
		&i.ID,
		&i.MilestoneID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.SortOrder,
		&i.DependsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSliceStatus = `-- name: UpdateSliceStatus :one
UPDATE slices
SET status = ?
WHERE id = ?
RETURNING id, milestone_id, title, status, phase, sort_order, depends_on, created_at, updated_at
`

type UpdateSliceStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateSliceStatus(ctx context.Context, arg UpdateSliceStatusParams) (Slice, error) {
	row := q.queryRow(ctx, q.updateSliceStatusStmt, updateSliceStatus, arg.Status, arg.ID)
	var i Slice
	err := row.Scan(
		&i.ID,
		&i.MilestoneID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.SortOrder,
		&i.DependsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
