// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id,
    slice_id,
    milestone_id,
    title,
    status,
    phase,
    sort_order,
    description,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, slice_id, milestone_id, title, status, phase, sort_order, description, created_at, updated_at
`

type CreateTaskParams struct {
	ID          string         `json:"id"`
	SliceID     string         `json:"slice_id"`
	MilestoneID string         `json:"milestone_id"`
	Title       string         `json:"title"`
	Status      string         `json:"status"`
	Phase       string         `json:"phase"`
	SortOrder   int64          `json:"sort_order"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.createTaskStmt, createTask,
		arg.ID,
		arg.SliceID,
		arg.MilestoneID,
		arg.Title,
		arg.Status,
		arg.Phase,
		arg.SortOrder,
		arg.Description,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SliceID,
		&i.MilestoneID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.SortOrder,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteTaskStmt, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, slice_id, milestone_id, title, status, phase, sort_order, description, created_at, updated_at FROM tasks
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.queryRow(ctx, q.getTaskStmt, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SliceID,
		&i.MilestoneID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.SortOrder,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByMilestone = `-- name: ListTasksByMilestone :many
SELECT id, slice_id, milestone_id, title, status, phase, sort_order, description, created_at, updated_at FROM tasks
WHERE milestone_id = ?
ORDER BY sort_order
`

func (q *Queries) ListTasksByMilestone(ctx context.Context, milestoneID string) ([]Task, error) {
	rows, err := q.query(ctx, q.listTasksByMilestoneStmt, listTasksByMilestone, milestoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SliceID,
			&i.MilestoneID,
			&i.Title,
			&i.Status,
			&i.Phase,
			&i.SortOrder,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksBySlice = `-- name: ListTasksBySlice :many
SELECT id, slice_id, milestone_id, title, status, phase, sort_order, description, created_at, updated_at FROM tasks
WHERE slice_id = ?
ORDER BY sort_order
`

func (q *Queries) ListTasksBySlice(ctx context.Context, sliceID string) ([]Task, error) {
	rows, err := q.query(ctx, q.listTasksBySliceStmt, listTasksBySlice, sliceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SliceID,
			&i.MilestoneID,
			&i.Title,
			&i.Status,
			&i.Phase,
			&i.SortOrder,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskPhase = `-- name: UpdateTaskPhase :one
UPDATE tasks
SET phase = ?
WHERE id = ?
RETURNING id, slice_id, milestone_id, title, status, phase, sort_order, description, created_at, updated_at
`

type UpdateTaskPhaseParams struct {
	Phase string `json:"phase"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateTaskPhase(ctx context.Context, arg UpdateTaskPhaseParams) (Task, error) {
	row := q.queryRow(ctx, q.updateTaskPhaseStmt, updateTaskPhase, arg.Phase, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SliceID,
		&i.MilestoneID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.SortOrder,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = ?
WHERE id = ?
RETURNING id, slice_id, milestone_id, title, status, phase, sort_order, description, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.queryRow(ctx, q.updateTaskStatusStmt, updateTaskStatus, arg.Status, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SliceID,
		&i.MilestoneID,
		&i.Title,
		&i.Status,
		&i.Phase,
		&i.SortOrder,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
